import {readFile, writeFile} from "node:fs/promises";
import {fileURLToPath} from "node:url";
import {parsePullRateConfig} from "../../core/domain/contracts.ts";
import {englishGroups,japaneseCodes,japaneseExceptions,observations,reviewedAt,sources} from "./research.mjs";

export function buildPackResearch(catalog) {
  const config={version:2,reviewedAt,note:"Generated by scripts/packs/build.mjs. Set-specific estimates; no game/era odds defaults. EV is partial. Unknown slots, prices and rates stay unavailable.",games:{},profiles:{},setProfiles:{pokemon:{},riftbound:{}},productProfiles:{},evidence:{}};
  for(const game of ["pokemon","riftbound"]) config.games[game]={default:{},sets:{},perPack:{default:{},sets:{}}};
  const slot=(label,count,tier=null)=>({label,count,tier});
  const profile=(id,game,language,cardsPerPack,slots,urls,notes)=>{
    config.profiles[id]={id,game,language,cardsPerPack,slots,sources:urls,notes};return id;
  };
  const en=(id,count,slots,notes="",url=sources.history)=>profile(id,"pokemon","en",count,slots,[url],notes);
  en("wotc",11,[slot("Common / Energy",7),slot("Uncommon",3),slot("Rare or higher",1)],"Vintage Energy collation and holo odds vary; structure only.");
  en("ex",9,[slot("Common",5,"Common"),slot("Uncommon",2,"Uncommon"),slot("Reverse foil / upgrade",1),slot("Rare or higher",1)]);
  en("ten",10,[slot("Common",5,"Common"),slot("Uncommon",3,"Uncommon"),slot("Reverse foil / gallery / upgrade",1),slot("Rare or higher",1)],"Special subset upgrades are not separately valued without matched odds. Energy/code extras excluded.");
  en("modern",10,[slot("Common",4,"Common"),slot("Uncommon",3,"Uncommon"),slot("Foil / upgrade",2),slot("Rare or higher",1)],"Energy and code extras excluded. Unresolved foil and rare-slot remainders are unvalued.",sources.modern);
  en("special10",10,[slot("Set-specific slots",10)],"Special-set collation requires its own measured slot mapping. Energy/code extras excluded.");
  const special={
    "Legendary Collection":[11,"Reverse foil plus set-specific base cards",sources.history],
    "Dragon Vault":[5,"Holo cards",sources.history],
    "Double Crisis":[7,"Set-specific cards","https://www.pokebeach.com/2015/03/all-english-double-crisis-scans"],
    "Detective Pikachu":[4,"Holo cards","https://www.pokemon.com/us/pokemon-tcg/product-gallery/detective-pikachu-tin"],
    "Celebrations":[4,"Holo / Classic Collection cards","https://www.pokemon.com/us/pokemon-tcg/product-gallery/celebrations-elite-trainer-box"],
    "McDonald's 25th Anniversary Promos":[4,"One holo plus three non-holo cards","https://www.pokebeach.com/2021/02/mcdonalds-25th-anniversary-set-will-actually-contain-50-cards-ahh"],
    "First Partner Collection 2026":[3,"Three promos; pool depends on series","https://www.pokemon.com/uk/pokemon-tcg/product-gallery/first-partner-illustration-collection-series-1"],
  };
  for(const [group,sets] of Object.entries(englishGroups)) for(const set of sets.split("|")) config.setProfiles.pokemon[set]=group;
  for(const [set,[count,label,url]] of Object.entries(special)) config.setProfiles.pokemon[set]=en(`special:${set}`,count,[slot(label,count)],"Structure only; rarity probabilities unavailable.",url);
  config.setProfiles.pokemon["Miscellaneous Cards & Products"]=profile("mixed","pokemon","en",null,[],[],"Mixed products: pack composition requires a product-specific source.");
  for(const product of catalog.filter(p=>p.game==="pokemon")) {
    const code=product.set.split(":")[0];
    if(!japaneseCodes.includes(code)) continue;
    // English SV10 is zero-padded elsewhere but collides with the Japanese code.
    if(product.set==="SV10: Destined Rivals") continue;
    const [count,url]=japaneseExceptions[code]??[5,code.startsWith("M")||code.startsWith("m")?"https://www.pokemon-card.com/ex/m1/":sources.jp];
    const id=`jp:${code}`;
    config.setProfiles.pokemon[product.set]=profile(id,"pokemon","ja",count,[slot("Japanese set-specific cards",count)],[url],"Japanese singles coverage and rarity odds are unavailable; English rates are never inherited.");
    if(["SV11B","SV11W"].includes(code)&&/deluxe/i.test(product.name)) config.productProfiles[product.productId]=profile(`${id}:deluxe`,"pokemon","ja",35,[slot("Deluxe pack cards",35)],[url],"35-card deluxe format; not a regular seven-card booster.");
  }
  const riftSources={Origins:sources.origins,Spiritforged:"https://assets.ctfassets.net/qgsv4hbp414k/jOq8CNlBWfFruUdG06yQr/7c2887aac4d76be4bdb33eadbc24a824/Riftbound_Spiritforged_Sell_Sheets__Aug_8_.pdf",Unleashed:"https://playriftbound.com/en-us/news/announcements/the-unleashed-overview/",Vendetta:"https://playriftbound.com/en-us/news/announcements/the-vendetta-overview/"};
  for(const [set,url] of Object.entries(riftSources)) config.setProfiles.riftbound[set]=profile(`rift:${set}`,"riftbound","en",14,[slot("Common",7,"Common"),slot("Uncommon",3,"Uncommon"),slot("Rare / Epic / premium",2),slot("Any-rarity foil",1),slot("Token / Rune",1)],[url],set==="Origins"?"Publisher estimates. Rare-slot remainder, foil and rune odds are unknown.":set==="Spiritforged"?"Display averages exceed six Epics and two special alt arts; these are not exact pack probabilities.":set==="Unleashed"?"Ultimate incidence is below 0.1%; a bound is not an exact EV rate.":"Crystal Rose follows base alt-art distribution; exact premium odds unpublished.");
  for(const [game,sets] of Object.entries(config.setProfiles)) for(const [set,id] of Object.entries(sets)) {
    const p=config.profiles[id];
    config.games[game].perPack.sets[set]=Object.fromEntries(p.slots.filter(s=>s.tier).map(s=>[s.tier,s.count]));
  }
  for(const observation of observations) {
    const {game,set,rates,...evidence}=observation;
    config.games[game].sets[set]=rates;
    config.evidence[`${game}|${set}`]={...evidence,reviewedAt};
  }
  // Verified exclusive rare-slot branches for SV Base. Other remainders are withheld
  // until their complete replacement rules have been reviewed.
  config.games.pokemon.replacements={"SV01: Scarlet & Violet Base Set":[{base:"Rare",count:1,upgrades:["Double Rare","Ultra Rare"]}]};
  for(const p of catalog.filter(p=>p.category==="Booster Packs"&&config.setProfiles[p.game])) if(!config.setProfiles[p.game][p.set]) throw new Error(`Unreviewed pack set: ${p.game}|${p.set}`);
  parsePullRateConfig(config);
  return config;
}

if(process.argv[1]===fileURLToPath(import.meta.url)) {
  const catalog=(await Promise.all(["pokemon","riftbound"].map(async game=>JSON.parse(await readFile(new URL(`../../public/data/sealed-${game}.json`,import.meta.url),"utf8"))))).flat();
  const config=buildPackResearch(catalog);
  await writeFile(new URL("../../public/data/pull-rates.json",import.meta.url),`${JSON.stringify(config,null,2)}\n`);
  console.log(`Built ${Object.values(config.setProfiles).reduce((n,sets)=>n+Object.keys(sets).length,0)} set profiles and ${Object.keys(config.evidence).length} sourced odds overlays.`);
}
