"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps -- keyed effects synchronize remote data and theme */
import {useEffect,useMemo,useRef,useState} from "react";
import index from "../tcg-index.json";
import SealedView from "./SealedView";
import DeferredImage from "./DeferredImage";
import {NumberedPagination,SegmentedView,SortableHeader,SortToolbar,type Direction} from "./MarketUI";
import {type PricePoint} from "./PriceChart";
import HistoryPanel,{movementTone,type HistoryMetric} from "./HistoryPanel";
import {fuzzyTextMatch,mapWithConcurrency,nearestChange,normalized,rangeStats} from "./market-utils";
import CardFilters,{type MovementFilters} from "./CardFilters";
import {SignalBadge,SignalTabs,StrictnessControl} from "./SignalControls";
import {marketSignal,type SignalSide,type SignalStrictness} from "./signal-utils";
import MultiSelectField from "./MultiSelectField";

type Game="pokemon"|"riftbound"|"magic"; type View="large"|"medium"|"text"|"full"; type SortKey="name"|"signal"|"set"|"market"|"low"|"high"|"change7"|"change30";
type Card={game:Game;section:string;productId:number;name:string;set:string;year:number;rarity:string;number:string;image:string;url:string;marketPrice:number;lowPrice:number|null;midPrice:number|null;highPrice:number|null;printing:string;priceChange:number|null};
type Point=PricePoint; type History={points:Point[];variant?:string;condition?:string;coverage:"exact"|"fallback"|"none";change7:number|null;change30:number|null;change90:number|null;low30:number|null;high30:number|null;historyLow:number|null;historyHigh:number|null};
const magicNames:Record<string,string>={C:"Common",U:"Uncommon",R:"Rare",M:"Mythic Rare",S:"Special",T:"Token",L:"Land",P:"Promo"};
const gameNames:Record<Game,string>={pokemon:"Pokémon",riftbound:"Riftbound",magic:"Magic: The Gathering"};
const displayLabel=(s:string)=>magicNames[s]??s;
const usd=(n:number|null)=>n==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:n>=100?0:2}).format(n);
const pct=(n:number|null)=>n==null?"—":`${n>=0?"+":""}${n.toFixed(1)}%`;
const cardMeta=(card:Card)=>{const cleanName=normalized(card.name),cleanNumber=normalized(card.number);return cleanNumber&&cleanName.endsWith(cleanNumber)?`${displayLabel(card.rarity)} · ${card.printing}`:`${card.number} · ${displayLabel(card.rarity)} · ${card.printing}`};
const fuzzyMatch=(card:Card,query:string)=>fuzzyTextMatch(`${card.name} ${card.set} ${card.number} ${card.rarity} ${card.printing}`,query);

const updated=new Date(index.sourceUpdatedAt).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"});
const defaultDirection=(key:SortKey):Direction=>key==="name"||key==="set"?"asc":"desc";
const singleViews:{key:View;label:string;icon:string}[]=[{key:"large",label:"Large",icon:"▦"},{key:"medium",label:"Medium",icon:"▤"},{key:"text",label:"Text",icon:"☷"},{key:"full",label:"Full",icon:"▥"}];
const productViews:{key:"singles"|"sealed";label:string;icon:string}[]=[{key:"singles",label:"Singles",icon:"◫"},{key:"sealed",label:"Sealed",icon:"▣"}];
const singleSorts:{label:string;key:SortKey}[]=[{label:"Card",key:"name"},{label:"Set",key:"set"},{label:"Market",key:"market"},{label:"30D Low",key:"low"},{label:"30D High",key:"high"},{label:"7D",key:"change7"},{label:"30D",key:"change30"}];
const signalSort={label:"Signal",key:"signal" as SortKey};
const cardHistoryMetrics=(card:Card,history?:History):HistoryMetric[]=>{const movement=(label:string,value:number|null|undefined):HistoryMetric=>({label,value:value===undefined?"…":pct(value??null),tone:movementTone(value)});return[{label:"Market",value:usd(card.marketPrice)},{label:"30D low",value:usd(history?.low30??null)},{label:"30D high",value:usd(history?.high30??null)},{label:"Hist low",value:usd(history?.historyLow??null)},movement("7 day",history?.change7),movement("30 day",history?.change30),movement("90 day",history?.change90)]};
function FullCard({card,history,rank}:{card:Card;history?:History;rank:number}){const values=[{label:"Market",value:usd(card.marketPrice)},{label:"30D low",value:usd(history?.low30??null)},{label:"30D high",value:usd(history?.high30??null)},{label:"Hist low",value:usd(history?.historyLow??null)},{label:"History high",value:usd(history?.historyHigh??null)},{label:"Median",value:usd(card.midPrice)},{label:"7 day",value:pct(history?.change7??null),tone:movementTone(history?.change7)},{label:"30 day",value:pct(history?.change30??null),tone:movementTone(history?.change30)},{label:"90 day",value:pct(history?.change90??null),tone:movementTone(history?.change90)}];return <a className="leader-row full-card" href={card.url} target="_blank" rel="noreferrer" role="row"><span className="position">{String(rank).padStart(2,"0")}</span><span className="full-art"><DeferredImage src={card.image} alt={`${card.name} card`}/></span><span className="full-data"><span className="full-title"><b>{card.name}</b><small>{cardMeta(card)}</small><em>{card.set} · {card.year}</em></span><span className="full-prices">{values.map(item=><span key={item.label}><small>{item.label}</small><b className={item.tone}>{item.value}</b></span>)}</span></span><span className="arrow">↗</span><span className="full-history"><HistoryPanel title="Near Mint market history" subtitle={history?.variant??card.printing} points={history?.points??[]} metrics={[]} large/></span></a>}
function HoverCard({card,history,signal}:{card:Card;history?:History;signal?:ReturnType<typeof marketSignal>}){return <span className="hover-card"><span className="hover-card-art"><DeferredImage src={card.image} alt={`${card.name} card`}/>{signal&&<SignalBadge signal={signal}/>}</span><HistoryPanel title="Near Mint market history" subtitle={history?.variant??card.printing} points={history?.points??[]} metrics={cardHistoryMetrics(card,history)} hint="Click again to open TCGplayer ↗"/></span>}

export default function Home(){
 const defaultRarities:Record<Game,string[]>={pokemon:["illustration-rares","special-illustration-rares"],riftbound:["overnumbered"],magic:["magic-m"]};
 const [game,setGame]=useState<Game>("pokemon"),[selectedRarities,setSelectedRarities]=useState<string[]>(defaultRarities.pokemon),[cards,setCards]=useState<Card[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[sort,setSort]=useState<SortKey>("market"),[direction,setDirection]=useState<Direction>("desc"),[view,setView]=useState<View>("medium"),[perPage,setPerPage]=useState(20),[page,setPage]=useState(1),[history,setHistory]=useState<Record<number,History>>({}),[serverTotal,setServerTotal]=useState<number|null>(null),[touchOpen,setTouchOpen]=useState<number|null>(null);
 const [mode,setMode]=useState<"singles"|"sealed">("singles"),[theme,setTheme]=useState<"dark"|"light">("dark"),[fontSize,setFontSize]=useState<"default"|"large">("default"),[settingsOpen,setSettingsOpen]=useState(false),[urlReady,setUrlReady]=useState(false);
 const settingsRef=useRef<HTMLDivElement>(null);
 const [signalView,setSignalView]=useState<SignalSide>("leaderboard"),[strictness,setStrictness]=useState<SignalStrictness>("balanced");
 const [minPrice,setMinPrice]=useState(""),[maxPrice,setMaxPrice]=useState(""),[selectedSets,setSelectedSets]=useState<string[]>([]),[movement,setMovement]=useState<MovementFilters>({up7:false,down7:false,up30:false,down30:false});
 useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setTouchOpen(null)};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[]);
 const rarityOptions=index.rarities[game].filter(option=>option.key!=="all"),section=selectedRarities[0]??"all",allRarities=!selectedRarities.length||selectedRarities.length===rarityOptions.length,selectedRarityNames=selectedRarities.map(key=>displayLabel(rarityOptions.find(option=>option.key===key)?.label??key)),rarityLabel=allRarities?"All":selectedRarityNames.length<=2?selectedRarityNames.join(" & "):`${selectedRarityNames.slice(0,2).join(", ")} & ${selectedRarityNames.length-2} More`;
 useEffect(()=>{const p=new URLSearchParams(location.search),nextGame=p.get("market") as Game|null,nextView=p.get("view") as View|null,nextSort=p.get("sort") as SortKey|null,nextSignal=p.get("signal") as SignalSide|null,nextStrictness=p.get("strictness") as SignalStrictness|null;if(nextGame&&nextGame in gameNames){setGame(nextGame);const valid=index.rarities[nextGame].filter(option=>option.key!=="all").map(option=>option.key),raw=p.get("rarity")?.split("|")??[],requested=raw.filter(key=>valid.includes(key));setSelectedRarities(raw.includes("all")||requested.length===valid.length?[]:requested.length?requested:defaultRarities[nextGame])}if(nextView&&["large","medium","text","full"].includes(nextView))setView(nextView);if(nextSort&&["name","signal","set","market","low","high","change7","change30"].includes(nextSort))setSort(nextSort);if(nextSignal&&["leaderboard","buy","sell"].includes(nextSignal)){setSignalView(nextSignal);if(nextSignal!=="leaderboard"&&!nextSort)setSort("signal")}if(nextStrictness&&["conservative","balanced","aggressive"].includes(nextStrictness))setStrictness(nextStrictness);setDirection(p.get("direction")==="asc"?"asc":"desc");setQuery(p.get("q")??"");setMinPrice(p.get("minPrice")??"");setMaxPrice(p.get("maxPrice")??"");setSelectedSets(p.get("sets")?.split("|").filter(Boolean)??[]);setMovement({up7:p.has("up7"),down7:p.has("down7"),up30:p.has("up30"),down30:p.has("down30")});setPage(Math.max(1,Number(p.get("page"))||1));setPerPage([20,30,40,50].includes(Number(p.get("perPage")))?Number(p.get("perPage")):20);setMode(p.get("mode")==="sealed"?"sealed":"singles");setUrlReady(true)},[]);
 useEffect(()=>{if(!urlReady)return;const p=new URLSearchParams({market:game,rarity:selectedRarities.length?selectedRarities.join("|"):"all",view,sort,direction,page:String(page),perPage:String(perPage),mode,signal:signalView,strictness});if(query)p.set("q",query);if(minPrice)p.set("minPrice",minPrice);if(maxPrice)p.set("maxPrice",maxPrice);if(selectedSets.length)p.set("sets",selectedSets.join("|"));for(const [key,value] of Object.entries(movement))if(value)p.set(key,"1");window.history.replaceState(null,"",`${location.pathname}?${p}`)},[urlReady,game,selectedRarities,view,sort,direction,page,perPage,mode,signalView,strictness,query,minPrice,maxPrice,selectedSets,movement]);
 useEffect(()=>{if(!urlReady)return;let live=true;setLoading(true);setServerTotal(null);const keys=selectedRarities.length?selectedRarities:rarityOptions.map(o=>o.key);if(game==="magic"&&keys.length===1){const p=new URLSearchParams({section:keys[0],q:query,sort,direction,page:String(page),perPage:String(perPage)});fetch(`/api/cards?${p}`).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(data=>{if(live){setCards(data.cards);setServerTotal(data.total);setLoading(false)}}).catch(()=>Promise.all(keys.map(key=>fetch(`/data/${key}.json`).then(r=>r.json()))).then(groups=>{if(live){const unique=new Map<number,Card>();groups.flat().forEach(c=>unique.set(c.productId,c));setCards([...unique.values()]);setLoading(false)}}));return()=>{live=false}}Promise.all(keys.map(key=>fetch(`/data/${key}.json`).then(r=>r.json()))).then(groups=>{if(live){const unique=new Map<number,Card>();groups.flat().forEach(c=>unique.set(c.productId,c));setCards([...unique.values()]);setLoading(false)}});return()=>{live=false}},[urlReady,game,selectedRarities.join("|"),game==="magic"&&selectedRarities.length===1?query:"",game==="magic"&&selectedRarities.length===1?sort:"",game==="magic"&&selectedRarities.length===1?direction:"",game==="magic"&&selectedRarities.length===1?page:0,game==="magic"&&selectedRarities.length===1?perPage:0]);
 const availableSets=useMemo(()=>[...new Set(cards.map(card=>card.set))].sort(),[cards]);
 const eligible=useMemo(()=>cards.filter(card=>(serverTotal!==null||fuzzyMatch(card,query))&&(!minPrice||card.marketPrice>=Number(minPrice))&&(!maxPrice||card.marketPrice<=Number(maxPrice))&&(!selectedSets.length||selectedSets.includes(card.set))),[cards,query,serverTotal,minPrice,maxPrice,selectedSets]);
 const signalFor=(card:Card)=>signalView==="leaderboard"?null:marketSignal(history[card.productId]?.points??[],signalView,strictness,card.marketPrice);
 const filtered=useMemo(()=>eligible.filter(card=>{const h=history[card.productId],match=(value:number|null|undefined,up:boolean,down:boolean)=>!up&&!down||(value!=null&&((up&&value>0)||(down&&value<0)));return match(h?.change7,movement.up7,movement.down7)&&match(h?.change30,movement.up30,movement.down30)&&(signalView==="leaderboard"||Boolean(signalFor(card)))}).sort((a,b)=>{const cardMovement=(c:Card,d:7|30)=>history[c.productId]?.[d===7?"change7":"change30"]??null;let x=0;if(sort==="signal")x=(signalFor(a)?.score??-1)-(signalFor(b)?.score??-1);else if(sort==="name")x=a.name.localeCompare(b.name);else if(sort==="set")x=a.set.localeCompare(b.set)||a.name.localeCompare(b.name);else if(sort==="low")x=(a.lowPrice??Infinity)-(b.lowPrice??Infinity);else if(sort==="high")x=(a.highPrice??Infinity)-(b.highPrice??Infinity);else if(sort==="change7"||sort==="change30"){const d=sort==="change7"?7:30,av=cardMovement(a,d),bv=cardMovement(b,d);x=av==null?1:bv==null?-1:av-bv}else x=a.marketPrice-b.marketPrice;return direction==="asc"?x:-x}),[eligible,sort,direction,history,movement,signalView,strictness]);
 const localFiltersActive=Boolean(minPrice||maxPrice||selectedSets.length||Object.values(movement).some(Boolean)),total=serverTotal!==null&&!localFiltersActive?serverTotal:filtered.length,pages=Math.max(1,Math.ceil(total/perPage)),visible=serverTotal!==null?filtered:filtered.slice((page-1)*perPage,page*perPage);
 useEffect(()=>{let live=true;const broad=Object.values(movement).some(Boolean)||signalView!=="leaderboard",targets=broad?eligible.slice(0,400):visible,missing=targets.filter(c=>!history[c.productId]);if(!missing.length)return;mapWithConcurrency(missing,4,async c=>{try{const response=await fetch(`/api/history?productId=${c.productId}&printing=${encodeURIComponent(c.printing)}`);if(!response.ok)throw new Error();const data=await response.json(),points:Point[]=data.points??[],month=rangeStats(points,30),all=rangeStats(points,36500);return [c.productId,{...data,points,change7:nearestChange(points,7),change30:nearestChange(points,30),change90:nearestChange(points,90),low30:month.low,high30:month.high,historyLow:all.low,historyHigh:all.high}] as const}catch{return [c.productId,{points:[],coverage:"none",change7:null,change30:null,change90:null,low30:null,high30:null,historyLow:null,historyHigh:null}] as const}}).then(entries=>{if(live)setHistory(old=>({...old,...Object.fromEntries(entries)}))});return()=>{live=false}},[(Object.values(movement).some(Boolean)||signalView!=="leaderboard"?eligible:visible).map(c=>c.productId).join(","),signalView,strictness]);
 const switchGame=(next:Game)=>{setGame(next);setSelectedRarities(defaultRarities[next]);setSelectedSets([]);setQuery("");setSort("market");setDirection("desc");setPage(1)};
 const changeSort=(next:SortKey)=>{setDirection(current=>sort===next?(current==="asc"?"desc":"asc"):defaultDirection(next));setSort(next);setPage(1)};
 useEffect(()=>{const saved=localStorage.getItem("raw-signal-theme")==="light"?"light":"dark";setTheme(saved);document.documentElement.dataset.theme=saved},[]);
 useEffect(()=>{const saved=localStorage.getItem("raw-signal-font-size")==="large"?"large":"default";setFontSize(saved);document.documentElement.dataset.fontSize=saved},[]);
 useEffect(()=>{if(!settingsOpen)return;const close=(event:PointerEvent)=>{if(!settingsRef.current?.contains(event.target as Node))setSettingsOpen(false)};window.addEventListener("pointerdown",close);return()=>window.removeEventListener("pointerdown",close)},[settingsOpen]);
 const toggleTheme=()=>setTheme(current=>{const next=current==="dark"?"light":"dark";document.documentElement.dataset.theme=next;localStorage.setItem("raw-signal-theme",next);return next});
 const changeFontSize=(next:"default"|"large")=>{setFontSize(next);document.documentElement.dataset.fontSize=next;localStorage.setItem("raw-signal-font-size",next)};
 const changeSignalView=(value:SignalSide)=>{setSignalView(value);setSort(value==="leaderboard"?"market":"signal");setDirection("desc");setPage(1)};
 const activeSorts=signalView==="leaderboard"?singleSorts:[singleSorts[0],signalSort,...singleSorts.slice(1)];
 const filterSummary=[query?{key:"query",label:`Search: ${query}`,clear:()=>setQuery("")}:null,minPrice||maxPrice?{key:"price",label:`Price: ${minPrice?`$${minPrice}`:"Any"}–${maxPrice?`$${maxPrice}`:"Any"}`,clear:()=>{setMinPrice("");setMaxPrice("")}}:null,selectedSets.length?{key:"sets",label:`${selectedSets.length} Set${selectedSets.length===1?"":"s"}`,clear:()=>setSelectedSets([])}:null,movement.up7?{key:"up7",label:"7D Increase",clear:()=>setMovement(value=>({...value,up7:false}))}:null,movement.down7?{key:"down7",label:"7D Decrease",clear:()=>setMovement(value=>({...value,down7:false}))}:null,movement.up30?{key:"up30",label:"30D Increase",clear:()=>setMovement(value=>({...value,up30:false}))}:null,movement.down30?{key:"down30",label:"30D Decrease",clear:()=>setMovement(value=>({...value,down30:false}))}:null].filter((item):item is {key:string;label:string;clear:()=>void}=>Boolean(item));
 return <main><nav className="topbar"><a className="brand" href="#top"><span>R</span> Raw Signal</a><div className="toplinks"><a href="#leaderboard">Rankings</a><a href="#method">Method</a><div className="display-settings" ref={settingsRef}><button className="settings-toggle" onClick={()=>setSettingsOpen(value=>!value)} aria-label="Display settings" aria-expanded={settingsOpen} aria-haspopup="menu"><span aria-hidden="true">⚙</span></button>{settingsOpen&&<div className="settings-menu" role="menu" aria-label="Display settings"><span>Font size</span><div className="font-size-options" role="group" aria-label="Font size"><button className={fontSize==="default"?"active":""} aria-pressed={fontSize==="default"} onClick={()=>changeFontSize("default")}><b>Aa</b><small>Default</small></button><button className={fontSize==="large"?"active":""} aria-pressed={fontSize==="large"} onClick={()=>changeFontSize("large")}><b>Aa</b><small>Larger</small></button></div></div>}</div><button className="theme-toggle" onClick={toggleTheme} aria-label={`Switch to ${theme==="dark"?"light":"dark"} mode`}><span aria-hidden="true">{theme==="dark"?"☀":"☾"}</span><b>{theme==="dark"?"Light":"Dark"}</b></button></div></nav>
 <header className="masthead" id="top"><p className="kicker">Daily TCG market intelligence</p><h1>The card market,<br/><span>without the noise.</span></h1><p className="dek">Price intelligence for Pokémon, Riftbound, and Magic: The Gathering—across raw singles and sealed products.</p></header>
 <div className="product-navigation"><SegmentedView value={mode} options={productViews} label="Product type" className="product-toggle" onChange={value=>{setMode(value);setPage(1)}}/></div>
 <div className="signal-navigation"><SignalTabs value={signalView} onChange={changeSignalView}/></div>
 {mode==="singles"?<><section className="market-strip"><label><span>Market</span><select aria-label="Singles market" value={game} onChange={e=>switchGame(e.target.value as Game)}><option value="pokemon">Pokémon</option><option value="riftbound">Riftbound</option><option value="magic">Magic: The Gathering</option></select></label><MultiSelectField label="Rarity" options={rarityOptions.map(option=>({key:option.key,label:displayLabel(option.label)}))} selected={selectedRarities} onChange={values=>{setSelectedRarities(values);setPage(1)}} allLabel="All rarities" searchable={false}/><div><span>Cards ranked</span><strong>{index.totals[game].toLocaleString()}</strong><small>total in {gameNames[game]}</small></div><label><span>Cards per page</span><select aria-label="Cards per page" value={perPage} onChange={e=>{setPerPage(Number(e.target.value));setPage(1)}}><option>20</option><option>30</option><option>40</option><option>50</option></select></label></section>
 <section className="leaderboard" id="leaderboard"><div className="section-heading is-filtered"><div><p>{gameNames[game]} market ranking</p><h2>{rarityLabel} {signalView==="leaderboard"?(selectedRarities.length>1&&!allRarities?"Leaderboards":"Leaderboard"):signalView==="buy"?"Hot Buys":"Hot Sells"}</h2><div className={`leader-filter-summary ${filterSummary.length>0||signalView!=="leaderboard"?"has-content":""}`} aria-label="Active leaderboard filters" aria-hidden={filterSummary.length===0&&signalView==="leaderboard"}><b>{total.toLocaleString()} Matches</b>{signalView!=="leaderboard"&&<span className="summary-signal">{strictness[0].toUpperCase()+strictness.slice(1)} Signals</span>}{filterSummary.map(item=><button type="button" key={item.key} title={`Remove ${item.label} filter`} aria-label={`Remove ${item.label} filter`} onClick={()=>{item.clear();setPage(1)}}>{item.label}<i aria-hidden="true">×</i></button>)}</div></div><span>{total.toLocaleString()} cards · updated {updated}</span></div>
 <div className={`controls ${signalView!=="leaderboard"?"has-strictness":""}`}><label><span>⌕</span><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Search card, set, or number"/></label>{signalView!=="leaderboard"&&<StrictnessControl value={strictness} onChange={value=>{setStrictness(value);setPage(1)}}/>}<CardFilters sets={availableSets} selectedSets={selectedSets} onSets={value=>{setSelectedSets(value);setPage(1)}} minPrice={minPrice} maxPrice={maxPrice} onMinPrice={value=>{setMinPrice(value);setPage(1)}} onMaxPrice={value=>{setMaxPrice(value);setPage(1)}} movement={movement} onMovement={value=>{setMovement(value);setPage(1)}} onReset={()=>{setMinPrice("");setMaxPrice("");setSelectedSets([]);setMovement({up7:false,down7:false,up30:false,down30:false});setPage(1)}}/><SegmentedView value={view} options={singleViews} label="Card view" onChange={v=>{setView(v);setPage(1)}}/></div>
 {view==="large"||view==="full"?<SortToolbar items={activeSorts} sort={sort} direction={direction} onSort={changeSort} label={`${view} card sorting`}/>:<div className={`table-head ${view} ${signalView!=="leaderboard"?"has-signal":""}`} role="row"><span role="columnheader">Rank</span>{activeSorts.map(item=><SortableHeader key={item.key} label={item.label} column={item.key} sort={sort} direction={direction} onSort={changeSort}/>) }<span aria-hidden="true"/></div>}
 <div className={`rows view-${view}`} role="rowgroup">{loading?<div className="row-skeletons" aria-label={`Loading ${rarityLabel} data`}>{Array.from({length:Math.min(8,perPage)},(_,i)=><span key={i}/>)}</div>:visible.map((c,i)=>{const h=history[c.productId],rank=(page-1)*perPage+i+1,signal=signalFor(c),columnSignal=signal&&(view==="medium"||view==="text");if(view==="full")return <span className="signal-card-wrap" key={c.productId}>{signal&&<SignalBadge signal={signal}/>}<FullCard card={c} history={h} rank={rank}/></span>;return <a className={`leader-row ${columnSignal?"has-signal":""} ${touchOpen===c.productId?"touch-open":""}`} href={c.url} target="_blank" rel="noreferrer" key={c.productId} role="row" onPointerEnter={event=>{if(view==="large"){const rect=event.currentTarget.getBoundingClientRect();event.currentTarget.dataset.expand=rect.right+430>window.innerWidth?"left":"right"}}} onClick={e=>{if(view!=="large"&&window.matchMedia("(hover: none)").matches&&touchOpen!==c.productId){e.preventDefault();setTouchOpen(c.productId)}}}><span className="position">{String(rank).padStart(2,"0")}</span><span className="identity"><DeferredImage src={c.image} alt=""/><span><b>{c.name}</b><small>{cardMeta(c)}</small>{signal&&view==="large"&&<SignalBadge signal={signal}/>}</span></span>{columnSignal&&<span className="signal-cell"><SignalBadge signal={signal}/></span>}<span className="set-name">{c.set}<small>{c.year}</small></span><span className="market-price">{usd(c.marketPrice)}<small>Mid {usd(c.midPrice)}</small></span><span className="low">{h?usd(h.low30):"…"}</span><span className="high">{h?usd(h.high30):"…"}</span><span className={`change change7 ${h?.change7!=null&&h.change7<0?"down":"up"}`}>{h?pct(h.change7):"…"}</span><span className={`change change30 ${h?.change30!=null&&h.change30<0?"down":"up"}`}>{h?pct(h.change30):"…"}</span><span className="arrow">↗</span><HoverCard card={c} history={h} signal={signal??undefined}/></a>})}</div>
 {!loading&&<NumberedPagination page={page} pages={pages} onChange={setPage} label="Leaderboard pages"/>}</section></>:<SealedView signalView={signalView} strictness={strictness} onStrictness={setStrictness}/>}
 <section className="method" id="method"><p className="kicker">The methodology</p><h2>How Raw Signal works.</h2><p className="method-intro">A daily, raw-card market view built from cached TCGplayer catalog and pricing data. It separates current listings from historical market signals, keeps printing variants explicit, and marks unavailable data instead of estimating it.</p><div className="method-grid"><p><b>Daily ingestion</b> A server-side sync reads TCGCSV’s cached TCGplayer groups, products, and prices, then joins them by product ID. Compact market files are prepared before the page loads.</p><p><b>Current price fields</b> Market approximates recent selling value. TCGCSV listing low, median, and listing high remain in card details; listing high can be distorted by price parking and is not treated as a valuation target.</p><p><b>30-day range columns</b> The leaderboard’s Low and High columns are calculated from Near Mint market-history observations in the most recent 30-day window. Missing history stays unavailable rather than falling back silently to listing extremes.</p><p><b>History and movement</b> Charts request TCGplayer’s quarterly English Near Mint history for the matching printing. Range buttons show 7, 30, or 90 days; changes compare with the nearest observation at or before each cutoff.</p><p><b>Search and pagination</b> Magic search, sorting, totals, and pagination run on the server so the browser receives only one page. Other markets use compact rarity files. Filters, view, sort, and page are encoded in the URL for sharing.</p><p><b>Images and sealed products</b> Text and prices render before near-viewport images. Failed art receives a readable fallback. Sealed market or median is compared with published MSRP; missing regional prices remain N/A.</p></div><p className="method-note">Coverage is limited to source-feed records and defined rarity groups. Prices are USD, may lag marketplaces, generally exclude shipping, and are informational—not financial advice.</p></section><footer><a className="brand" href="#top"><span>R</span> Raw Signal</a><p>Current catalog and listing prices from <a href="https://tcgcsv.com/docs" target="_blank" rel="noreferrer">TCGCSV</a>; Near Mint market history from TCGplayer; sealed MSRP from publisher sources.</p></footer></main>
}
