"use client";
import { useEffect, useMemo, useState } from "react";
import index from "../tcg-index.json";
import SealedView from "./SealedView";
import DeferredImage from "./DeferredImage";
type Game="pokemon"|"riftbound"|"magic";
type Card={game:Game;section:string;productId:number;name:string;set:string;year:number;rarity:string;number:string;image:string;url:string;marketPrice:number;lowPrice:number|null;midPrice:number|null;printing:string;priceChange:number|null};
type Point={date:string;price:number};
type History={points:Point[];variant?:string;condition?:string;coverage:"exact"|"fallback"|"none";change7:number|null;change30:number|null};
const magicNames:Record<string,string>={C:"Common",U:"Uncommon",R:"Rare",M:"Mythic Rare",S:"Special",T:"Token",L:"Land",P:"Promo"};
const gameNames:Record<Game,string>={pokemon:"Pokémon",riftbound:"Riftbound",magic:"Magic: The Gathering"};
const displayLabel=(label:string)=>magicNames[label]??label;
const usd=(n:number|null)=>n==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:n>=100?0:2}).format(n);
const pct=(n:number|null)=>n==null?"—":`${n>=0?"+":""}${n.toFixed(1)}%`;
const nearestChange=(points:Point[],days:number)=>{if(points.length<2)return null;const latest=points.at(-1)!;const target=new Date(`${latest.date}T00:00:00Z`);target.setUTCDate(target.getUTCDate()-days);const prior=[...points].reverse().find(p=>new Date(`${p.date}T00:00:00Z`)<=target);return prior?((latest.price-prior.price)/prior.price)*100:null};
function Sparkline({points}:{points:Point[]}){if(points.length<2)return <span className="no-chart">History unavailable</span>;const values=points.map(p=>p.price),min=Math.min(...values),max=Math.max(...values),span=max-min||1;const coords=points.map((p,i)=>`${(i/(points.length-1))*240},${70-((p.price-min)/span)*62}`).join(" ");return <svg className="sparkline" viewBox="0 0 240 76" role="img" aria-label="Quarterly Near Mint market price history"><polyline points={coords}/></svg>}
const updated=new Date(index.sourceUpdatedAt).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"});
export default function Home(){
 const [game,setGame]=useState<Game>("pokemon"),[section,setSection]=useState(index.rarities.pokemon[0].key),[cards,setCards]=useState<Card[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[sort,setSort]=useState("market"),[view,setView]=useState("medium"),[perPage,setPerPage]=useState(20),[page,setPage]=useState(1),[history,setHistory]=useState<Record<number,History>>({});
 const [mode,setMode]=useState<"singles"|"sealed">("singles");
 const rarityOptions=index.rarities[game]; const rarityLabel=displayLabel(rarityOptions.find(x=>x.key===section)?.label??rarityOptions[0].label);
 useEffect(()=>{let live=true;setLoading(true);fetch(`/data/${section}.json`).then(r=>r.json()).then(d=>{if(live){setCards(d);setLoading(false);setPage(1)}});return()=>{live=false}},[section]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return cards.filter(c=>!q||`${c.name} ${c.set} ${c.number}`.toLowerCase().includes(q)).sort((a,b)=>sort==="low"?(a.lowPrice??Infinity)-(b.lowPrice??Infinity):sort==="drop"?(a.priceChange??0)-(b.priceChange??0):sort==="increase"?(b.priceChange??0)-(a.priceChange??0):sort==="name"?a.name.localeCompare(b.name):b.marketPrice-a.marketPrice)},[cards,query,sort]);
 const pages=Math.max(1,Math.ceil(filtered.length/perPage)),visible=filtered.slice((page-1)*perPage,page*perPage);
 useEffect(()=>{let live=true;const missing=visible.filter(card=>!history[card.productId]);if(!missing.length)return;Promise.all(missing.map(async card=>{try{const response=await fetch(`/api/history?productId=${card.productId}&printing=${encodeURIComponent(card.printing)}`);if(!response.ok)throw new Error();const data=await response.json();const points:Point[]=data.points??[];return [card.productId,{...data,points,change7:nearestChange(points,7),change30:nearestChange(points,30)}] as const}catch{return [card.productId,{points:[],coverage:"none",change7:null,change30:null}] as const}})).then(entries=>{if(live)setHistory(old=>({...old,...Object.fromEntries(entries)}))});return()=>{live=false}},[visible.map(c=>c.productId).join(",")]);
 const switchGame=(next:Game)=>{setGame(next);setSection(index.rarities[next][0].key);setQuery("");setSort("market")};
 return <main><nav className="topbar"><a className="brand" href="#top"><span>R</span> Raw Signal</a><div className="toplinks"><a href="#leaderboard">Rankings</a><a href="#method">Method</a></div></nav>
 <header className="masthead" id="top"><p className="kicker">Daily TCG market intelligence</p><h1>The card market,<br/><span>without the noise.</span></h1><p className="dek">Price intelligence for Pokémon, Riftbound, and Magic: The Gathering—across raw singles and sealed products.</p></header>
 <div className="mode-tabs" role="tablist" aria-label="Product type"><button role="tab" aria-selected={mode==="singles"} className={mode==="singles"?"active":""} onClick={()=>setMode("singles")}>Singles</button><button role="tab" aria-selected={mode==="sealed"} className={mode==="sealed"?"active":""} onClick={()=>setMode("sealed")}>Sealed</button></div>
 {mode==="singles"?<><section className="market-strip">
  <label><span>Market</span><select value={game} onChange={e=>switchGame(e.target.value as Game)}><option value="pokemon">Pokémon</option><option value="riftbound">Riftbound</option><option value="magic">Magic: The Gathering</option></select></label>
  <label><span>Rarity</span><select value={section} onChange={e=>setSection(e.target.value)}>{rarityOptions.map(x=><option key={x.key} value={x.key}>{displayLabel(x.label)}</option>)}</select></label>
  <div><span>Cards ranked</span><strong>{index.totals[game].toLocaleString()}</strong><small>total in {gameNames[game]}</small></div>
  <label><span>Cards per page</span><select value={perPage} onChange={e=>{setPerPage(Number(e.target.value));setPage(1)}}><option>20</option><option>30</option><option>40</option><option>50</option></select></label>
 </section>
 <section className="leaderboard" id="leaderboard"><div className="section-heading"><div><p>{gameNames[game]} market ranking</p><h2>{rarityLabel} Leaderboard</h2></div><span>{filtered.length.toLocaleString()} cards · updated {updated}</span></div>
 <div className="controls"><label><span>⌕</span><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Search card, set, or number"/></label><select value={sort} onChange={e=>{setSort(e.target.value);setPage(1)}}><option value="market">Market price: high to low</option><option value="low">Lowest listing first</option><option value="drop">Largest price drops</option><option value="increase">Largest price increases</option><option value="name">Card name: A–Z</option><option value="traded" disabled>Most traded — not provided by TCGCSV</option></select><select value={view} onChange={e=>setView(e.target.value)} aria-label="Card view"><option value="large">Large images</option><option value="medium">Medium images</option><option value="text">Text only</option></select></div>
 <div className={`table-head ${view}`}><span>Rank</span><span>Card</span><span>Set</span><span>Low</span><span>Market</span><span>7D</span><span>30D</span></div>
 <div className={`rows view-${view}`}>{loading?<div className="empty">Loading {rarityLabel} data…</div>:visible.map((c,i)=>{const h=history[c.productId];return <a className="leader-row" href={c.url} target="_blank" rel="noreferrer" key={c.productId}><span className="position">{String((page-1)*perPage+i+1).padStart(2,"0")}</span><span className="identity"><DeferredImage src={c.image} alt=""/><span><b>{c.name}</b><small>{c.number} · {displayLabel(c.rarity)} · {c.printing}</small></span></span><span className="set-name">{c.set}<small>{c.year}</small></span><span className="low">{usd(c.lowPrice)}</span><span className="market-price">{usd(c.marketPrice)}<small>Mid {usd(c.midPrice)}</small></span><span className={`change change7 ${h?.change7!=null&&h.change7<0?"down":"up"}`}>{h?pct(h.change7):"…"}</span><span className={`change change30 ${h?.change30!=null&&h.change30<0?"down":"up"}`}>{h?pct(h.change30):"…"}</span><span className="arrow">↗</span><span className="hover-card"><DeferredImage className="hover-image" src={c.image} alt={`${c.name} card`}/><span className="history-panel"><div className="history-title"><small>Near Mint market history</small><b>{h?.variant??c.printing}</b></div><Sparkline points={h?.points??[]}/><div className="history-stats"><span><small>Low</small><b>{usd(c.lowPrice)}</b></span><span><small>Market</small><b>{usd(c.marketPrice)}</b></span><span><small>7 day</small><b className={h?.change7!=null&&h.change7<0?"down":"up"}>{h?pct(h.change7):"…"}</b></span><span><small>30 day</small><b className={h?.change30!=null&&h.change30<0?"down":"up"}>{h?pct(h.change30):"…"}</b></span></div>{h?.coverage==="fallback"&&<em>Closest Near Mint printing shown</em>}</span></span></a>})}</div>
 {!loading&&<div className="pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>← Previous</button><span>Page <b>{page}</b> of {pages}</span><button disabled={page===pages} onClick={()=>setPage(p=>p+1)}>Next →</button></div>}</section></>:<SealedView/>}
 <section className="method" id="method"><p className="kicker">The methodology</p><h2>Current price, with market context.</h2><div className="method-grid"><p><b>Price points</b> Low, mid, and market prices come from TCGCSV’s daily TCGplayer export. Market price reflects recent completed sales; low and mid describe current listings.</p><p><b>7 & 30 day movement</b> Percentage change uses TCGplayer’s Near Mint English market-price history, matching the card’s printing where available and the closest observation at or before each cutoff.</p><p><b>Price graphs</b> Hover a row to see the quarterly market-price series. Charts are condition-specific and never blend graded cards with raw cards.</p></div></section><footer><a className="brand" href="#top"><span>R</span> Raw Signal</a><p>Current prices from <a href="https://tcgcsv.com/" target="_blank" rel="noreferrer">TCGCSV</a>; historical Near Mint market prices from TCGplayer. Prices may lag and exclude shipping.</p></footer></main>
}
