"use client";
import { useMemo, useState } from "react";
import dataset from "../cards.json";
type Card = (typeof dataset.cards)[number];
type SortKey = "discount" | "price" | "volume";
const volumeRank = { High: 3, Medium: 2, Low: 1 } as const;
const money = (value: number | null) => value == null ? "—" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value);
function displayTitle(card: Card) { return card.title.replace(new RegExp(`\\s+Pokemon ${card.set.replace(/[.*+?^${}()|[\\]\\]/g, "\\$&")}$`, "i"), ""); }
export default function Home() {
  const [query, setQuery] = useState(""); const [volume, setVolume] = useState("All"); const [sort, setSort] = useState<SortKey>("discount");
  const cards = useMemo(() => { const q=query.trim().toLowerCase(); return [...dataset.cards].filter(c=>(!q||`${c.title} ${c.set}`.toLowerCase().includes(q))&&(volume==="All"||c.volume===volume)).sort((a,b)=>sort==="price"?a.current-b.current:sort==="volume"?volumeRank[b.volume]-volumeRank[a.volume]:b.pctFromHigh-a.pctFromHigh); }, [query,volume,sort]);
  return <main>
    <header className="hero"><div className="eyebrow"><span className="live-dot"/> Raw market scan · Aug 22, 2026</div><h1>Cards below<br/><em>their recent highs.</em></h1><p className="intro">50 modern and mid-era Pokémon singles, screened with PriceCharting raw history and TCGplayer activity. A watchlist—not a buy list.</p><div className="hero-stats"><div><strong>50</strong><span>raw cards</span></div><div><strong>{Math.round(dataset.cards.reduce((s,c)=>s+c.pctFromHigh,0)/dataset.cards.length)}%</strong><span>avg. below high</span></div><div><strong>{dataset.cards.filter(c=>c.volume==="High").length}</strong><span>high volume</span></div></div></header>
    <section className="method"><span>How to read this</span><p><b>Below high</b> compares today’s PriceCharting ungraded value with the highest monthly ungraded value in the trailing 12 months. <b>TCG volume</b> counts visible Near Mint TCGplayer sales in the latest 30-day window: High 12+, Medium 4–11, Low 0–3.</p></section>
    <section className="toolbar"><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search card or set" aria-label="Search card or set"/></label><div className="control-row"><select value={volume} onChange={e=>setVolume(e.target.value)} aria-label="Filter by volume"><option>All</option><option>High</option><option>Medium</option><option>Low</option></select><select value={sort} onChange={e=>setSort(e.target.value as SortKey)} aria-label="Sort cards"><option value="discount">Biggest discount</option><option value="price">Lowest price</option><option value="volume">Most traded</option></select></div><div className="result-count">Showing <b>{cards.length}</b> cards</div></section>
    <section className="grid" aria-live="polite">{cards.map((card,index)=><article className="card" key={card.pricecharting}><div className="rank">{String(index+1).padStart(2,"0")}</div><div className="image-wrap"><img src={card.image} alt={`${displayTitle(card)} card`} loading="lazy"/><div className="discount">↓ {card.pctFromHigh}%</div></div><div className="card-body"><div className="set">{card.set}</div><h2>{displayTitle(card)}</h2><div className="prices"><div><span>Raw now</span><strong>{money(card.current)}</strong><small>PriceCharting</small></div><div><span>Recent high</span><strong>{money(card.recentHigh)}</strong><small>trailing 12 mo.</small></div></div><div className="tcg-row"><span className={`volume ${card.volume.toLowerCase()}`}><i/>{card.volume} volume</span><span>{card.sales30} sales / 30d</span></div><div className="market">TCGplayer market <b>{money(card.tcgMarket)}</b></div><div className="links"><a href={card.pricecharting} target="_blank" rel="noreferrer">Price history ↗</a><a href={card.tcgplayer!} target="_blank" rel="noreferrer">Shop TCGplayer ↗</a></div></div></article>)}</section>
    <footer><b>Raw Signal</b><p>Prices move. Check condition, language, printing, and the live listing before buying. This research is informational and isn’t financial advice.</p><span>Sources: PriceCharting · TCGplayer</span></footer>
  </main>;
}
