"use client";
/* eslint-disable @next/next/no-html-link-for-pages -- detail navigation preserves exact leaderboard URLs */
import {useEffect,useMemo,useState} from "react";
import DeferredImage from "./DeferredImage";
import PriceChart from "./PriceChart";
import SaleScenario from "./SaleScenario";
import {calculateSealedScenario,type SealedScenario} from "./data/catalog-query";
import {detailPercentile} from "./domain/detail";
import {distanceAbove,distanceBelow,historyDepth,rangePosition,rangeWidth} from "./domain/detail-metrics";
import {formatPercent,formatUsd,formatUtcDate} from "./domain/formatters";
import type {CatalogDetail,DetailPriceVariant,PriceHistory,SealedDetail} from "./domain/types";

const emptyHistory:PriceHistory={points:[],coverage:"none",change7:null,change30:null,change90:null,low30:null,high30:null,historyLow:null,historyHigh:null};
const numberParam=(params:URLSearchParams,key:string,fallback:number)=>{const raw=params.get(key);if(raw==null||raw.trim()==="")return fallback;const value=Number(raw);return Number.isFinite(value)?value:fallback};
const pct=(value:number|null)=>value==null?"N/A":formatPercent(value);

function Metric({label,value,hint,tone}:{label:string;value:string;hint?:string;tone?:"up"|"down"}){return <div className="detail-metric"><small>{label}</small><b className={tone}>{value}</b>{hint&&<span>{hint}</span>}</div>}

function DetailChrome({fallback}:{fallback:string}){
 const [theme,setTheme]=useState<"dark"|"light">(()=>typeof document!=="undefined"&&document.documentElement.dataset.theme==="light"?"light":"dark");
 const toggle=()=>{const next=theme==="dark"?"light":"dark";setTheme(next);document.documentElement.dataset.theme=next;localStorage.setItem("raw-signal-theme",next)};
 return <nav className="topbar detail-topbar"><a className="brand" href="/"><span>R</span> Raw Signal</a><div className="detail-nav-actions"><button type="button" className="detail-back" onClick={()=>history.length>1?history.back():location.assign(fallback)}>← Back to results</button><button type="button" className="theme-toggle" onClick={toggle} aria-label={`Switch to ${theme==="dark"?"light":"dark"} mode`}><span aria-hidden="true">{theme==="dark"?"☀":"☾"}</span><b>{theme==="dark"?"Light":"Dark"}</b></button></div></nav>
}

function SourceFacts({detail}:{detail:CatalogDetail}){const source=detail.source,premium=detail.kind==="sealed"&&detail.msrp&&detail.marketPrice!=null?(detail.marketPrice-detail.msrp)/detail.msrp*100:null,rows=[source.setAbbreviation&&["Set abbreviation",source.setAbbreviation],source.publishedOn&&["Set published",source.publishedOn.slice(0,10)],source.modifiedOn&&["Product updated",source.modifiedOn.slice(0,10)],source.imageCount!=null&&["Images available",String(source.imageCount)],source.isPresale!=null&&["Presale",source.isPresale?"Yes":"No"],premium!=null&&["MSRP premium",pct(premium)]].filter(Boolean) as string[][];return rows.length?<dl className="detail-facts">{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>:<p className="detail-unavailable">Additional source metadata is unavailable for this product.</p>}

function SimilarItems({detail}:{detail:CatalogDetail}){return <section className="detail-section"><header><span>Explore the market</span><h2>Similar {detail.kind==="single"?"cards":"products"}</h2></header>{detail.similar.length?<div className="similar-grid">{detail.similar.map(item=><a href={item.href} className="similar-card" key={`${item.kind}:${item.productId}`}><DeferredImage src={item.image} alt=""/><span><b>{item.name}</b><small>{item.set}</small><strong>{formatUsd(item.marketPrice,"N/A")}</strong></span></a>)}</div>:<p className="detail-unavailable">No close comparisons are available.</p>}</section>}

function SealedScenarioPanel({detail}:{detail:SealedDetail}){
 const initial=useMemo(()=>new URLSearchParams(typeof location==="undefined"?"":location.search),[]),[basis,setBasis]=useState<"market"|"median">(initial.get("basis")==="median"?"median":"market"),[keepPct,setKeepPct]=useState(numberParam(initial,"keepPct",100)),[taxOn,setTaxOn]=useState(initial.get("taxOn")==="1"),[taxRate,setTaxRate]=useState(numberParam(initial,"taxRate",8)),[shipping,setShipping]=useState(numberParam(initial,"shipping",0)),[profitableOnly,setProfitableOnly]=useState(false);
 const scenario:SealedScenario={basis,keepPct,taxOn,taxRate,shipping},result=calculateSealedScenario(detail,scenario);
 useEffect(()=>{const url=new URL(location.href);url.searchParams.set("basis",basis);if(keepPct===100)url.searchParams.delete("keepPct");else url.searchParams.set("keepPct",String(keepPct));if(taxOn)url.searchParams.set("taxOn","1");else url.searchParams.delete("taxOn");if(taxRate===8)url.searchParams.delete("taxRate");else url.searchParams.set("taxRate",String(taxRate));if(shipping)url.searchParams.set("shipping",String(shipping));else url.searchParams.delete("shipping");history.replaceState(null,"",url)},[basis,keepPct,taxOn,taxRate,shipping]);
 return <section className="detail-section detail-scenario"><header><span>What-if calculator</span><h2>Sale scenario</h2><div className="price-basis" aria-label="Scenario price basis"><i aria-hidden="true"/><button className={basis==="market"?"active":""} onClick={()=>setBasis("market")}>Market</button><button className={basis==="median"?"active":""} onClick={()=>setBasis("median")}>Median</button></div></header><SaleScenario keepPct={keepPct} onKeepPct={setKeepPct} taxOn={taxOn} onTaxOn={setTaxOn} taxRate={taxRate} onTaxRate={setTaxRate} shipping={shipping} onShipping={setShipping} profitableOnly={profitableOnly} onProfitableOnly={setProfitableOnly}/><div className="detail-scenario-results"><Metric label="Selected value" value={formatUsd(result.value,"N/A")}/><Metric label="Total cost" value={formatUsd(result.cost,"N/A")}/><Metric label="Net proceeds" value={formatUsd(result.proceeds,"N/A")}/><Metric label="Estimated profit" value={result.profit==null?"N/A":`${result.profit>=0?"+":""}${formatUsd(result.profit)}`} tone={result.profit==null?undefined:result.profit<0?"down":"up"}/><Metric label="Return" value={pct(result.profitPct)} tone={result.profitPct==null?undefined:result.profitPct<0?"down":"up"}/></div><p className="detail-note">Scenario inputs are estimates, not predictions. Missing MSRP or market pricing remains N/A.</p></section>
}

export default function ProductDetailPage({detail,market}:{detail:CatalogDetail;market?:string}){
 const [variant,setVariant]=useState(detail.priceVariants.find(item=>item.printing===(detail.kind==="single"?detail.printing:"Sealed"))??detail.priceVariants[0]),[historyResult,setHistoryResult]=useState<{key:string;value:PriceHistory|null;error:boolean}>({key:"",value:null,error:false});
 const fallback=detail.kind==="single"?`/?mode=singles&market=${detail.game}`:`/?mode=sealed&market=${market??detail.game}`,current=variant?.marketPrice??detail.marketPrice,printing=variant?.printing??(detail.kind==="single"?detail.printing:"Sealed"),historyKey=`${detail.kind}:${detail.productId}:${printing}`;
 useEffect(()=>{const controller=new AbortController(),params=new URLSearchParams({productId:String(detail.productId),printing});if(detail.kind==="sealed")params.set("sealed","1");fetch(`/api/history?${params}`,{signal:controller.signal}).then(response=>{if(!response.ok)throw new Error();return response.json()}).then(value=>setHistoryResult({key:historyKey,value:value as PriceHistory,error:false})).catch(error=>{if(error.name!=="AbortError")setHistoryResult({key:historyKey,value:null,error:true})});return()=>controller.abort()},[detail.kind,detail.productId,printing,historyKey]);
 const historyData=historyResult.key===historyKey?historyResult.value:null,historyError=historyResult.key===historyKey&&historyResult.error,h=historyData??emptyHistory,depth=historyDepth(historyData),rankPct=detailPercentile(detail),position=rangePosition(current,h.historyLow,h.historyHigh);
 const sourceLabel=detail.source.sourceUpdatedAt?`Source updated ${detail.source.sourceUpdatedAt.slice(0,10)}`:"Current TCGCSV / TCGplayer snapshot";
 return <main className="detail-page"><DetailChrome fallback={fallback}/><article className="detail-content"><a className="detail-breadcrumb" href={fallback}>Market rankings / {detail.game} / {detail.set}</a><section className="detail-hero"><div className="detail-art"><DeferredImage src={detail.image} alt={`${detail.name} ${detail.kind==="single"?"card":"product"}`}/></div><div className="detail-overview"><span className="kicker">{detail.kind==="single"?`${detail.rarity} · ${detail.printing}`:`${detail.category} · sealed product`}</span><h1>{detail.name}</h1><p>{detail.set}{detail.kind==="single"?` · ${detail.number}`:""}</p><div className="detail-primary-price"><small>TCGplayer market</small><strong>{formatUsd(current,"N/A")}</strong>{variant&&<span>{variant.printing}</span>}</div><div className="detail-actions"><a className="tcgplayer-button" href={detail.url} target="_blank" rel="noopener noreferrer">{detail.exactTcgplayerUrl?"View":"Search"} on TCGplayer ↗</a></div><div className="detail-overview-grid"><Metric label="Listing low" value={formatUsd(variant?.lowPrice,"N/A")}/><Metric label="Direct low" value={formatUsd(variant?.directLowPrice,"N/A")}/><Metric label="Median" value={formatUsd(variant?.midPrice,"N/A")}/><Metric label="Listing high" value={formatUsd(variant?.highPrice,"N/A")} hint="May include parked listings"/>{detail.kind==="sealed"&&<Metric label="MSRP" value={formatUsd(detail.msrp,"N/A")} hint={detail.msrpSource??"Unavailable"}/>}<Metric label="Market rank" value={detail.marketRank?`#${detail.marketRank} of ${detail.marketRankTotal}`:"N/A"} hint={rankPct?`Top ${100-rankPct+1}% of peers`:undefined}/></div></div></section>
 <section className="detail-section detail-history"><header><span>Market movement</span><h2>Price history</h2>{detail.priceVariants.length>1&&<label className="detail-variant"><span>Printing</span><select value={variant?.printing} onChange={event=>setVariant(detail.priceVariants.find(item=>item.printing===event.target.value) as DetailPriceVariant)}>{detail.priceVariants.map(item=><option key={item.printing}>{item.printing}</option>)}</select></label>}</header>{historyError?<p className="detail-unavailable">Price history is temporarily unavailable.</p>:!historyData?<div className="detail-chart-loading" aria-label="Loading price history"/>:<><PriceChart points={h.points} label="market" large/><div className="detail-history-grid"><Metric label="7 day" value={pct(h.change7)} tone={h.change7==null?undefined:h.change7<0?"down":"up"}/><Metric label="30 day" value={pct(h.change30)} tone={h.change30==null?undefined:h.change30<0?"down":"up"}/><Metric label="90 day" value={pct(h.change90)} tone={h.change90==null?undefined:h.change90<0?"down":"up"}/><Metric label="30D low" value={formatUsd(h.low30,"N/A")}/><Metric label="30D high" value={formatUsd(h.high30,"N/A")}/><Metric label="Historic low" value={formatUsd(h.historyLow,"N/A")}/><Metric label="Historic high" value={formatUsd(h.historyHigh,"N/A")}/><Metric label="Above historic low" value={pct(distanceAbove(current,h.historyLow))}/><Metric label="Below historic high" value={pct(distanceBelow(current,h.historyHigh))}/><Metric label="Historic range position" value={position==null?"N/A":`${position.toFixed(0)}%`}/><Metric label="30D range width" value={pct(rangeWidth(h.low30,h.high30))}/><Metric label="Observations" value={String(depth.count)} hint={depth.first&&depth.last?`${formatUtcDate(depth.first,true)} – ${formatUtcDate(depth.last,true)}`:undefined}/></div><p className="detail-note">{h.coverage==="exact"?"Exact":"Fallback"} {h.variant??variant?.printing} · {h.condition??"market"} history.</p></>}</section>
 {detail.kind==="sealed"&&<SealedScenarioPanel detail={detail}/>}<section className="detail-section"><header><span>Product overview</span><h2>{detail.kind==="single"?"Card details":"Product details"}</h2></header><div className="detail-info-layout"><SourceFacts detail={detail}/>{detail.metadata.length?<dl className="detail-metadata">{detail.metadata.map(field=><div key={`${field.name}:${field.value}`}><dt>{field.label}</dt><dd>{field.value}</dd></div>)}</dl>:<p className="detail-unavailable">No additional category-specific fields were supplied for this product.</p>}</div>{detail.source.presaleNote&&<p className="detail-note">Presale note: {detail.source.presaleNote}</p>}</section><SimilarItems detail={detail}/><section className="detail-provenance"><b>Data notes</b><p>{sourceLabel}. TCGplayer listing highs can be distorted by price parking. Market prices and history are informational and are not guarantees of future value.</p></section></article></main>;
}
