"use client";
import { useEffect, useMemo, useState } from "react";
import DeferredImage from "./DeferredImage";

type Game="pokemon"|"onepiece"|"riftbound"|"magic";
type Basis="market"|"median";
type Product={game:Game;productId:number;name:string;set:string;category:string;image:string|null;url:string;msrp:number;marketPrice:number|null;midPrice:number|null;profit:number|null;profitPct:number|null;msrpSource:string};
const games:Record<Game,string>={pokemon:"Pokémon",onepiece:"One Piece",riftbound:"Riftbound",magic:"Magic: The Gathering"};
const usd=(value:number|null)=>value==null?"N/A":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:value>=100?0:2}).format(value);

export default function SealedView(){
 const [game,setGame]=useState<Game>("pokemon"),[products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[setFilter,setSetFilter]=useState("all"),[sort,setSort]=useState("profitPct"),[perPage,setPerPage]=useState(20),[page,setPage]=useState(1);
 const [basis,setBasis]=useState<Basis>("market"),[keepPct,setKeepPct]=useState(100),[taxOn,setTaxOn]=useState(false),[taxRate,setTaxRate]=useState(8),[shipping,setShipping]=useState(0),[profitableOnly,setProfitableOnly]=useState(false);
 useEffect(()=>{let active=true;setLoading(true);fetch(`/data/sealed-${game}.json`).then(response=>response.json()).then(data=>{if(active){setProducts(data);setLoading(false);setPage(1);setSetFilter("all")}});return()=>{active=false}},[game]);
 const sets=useMemo(()=>[...new Set(products.map(product=>product.set))].sort(),[products]);
 const calculate=(product:Product)=>{const value=basis==="median"?(product.midPrice??product.marketPrice):product.marketPrice,cost=product.msrp*(taxOn?1+taxRate/100:1)+shipping;if(value==null)return{value:null,cost,proceeds:null,profit:null,profitPct:null};const proceeds=value*keepPct/100,profit=proceeds-cost;return{value,cost,proceeds,profit,profitPct:cost?profit/cost*100:0}};
 const filtered=useMemo(()=>{const needle=query.trim().toLowerCase();return products.filter(product=>{const result=calculate(product);return(setFilter==="all"||product.set===setFilter)&&(!needle||`${product.name} ${product.set}`.toLowerCase().includes(needle))&&(!profitableOnly||(result.profit??-Infinity)>0)}).sort((a,b)=>{const ac=calculate(a),bc=calculate(b),desc=(av:number|null,bv:number|null)=>(bv??-Infinity)-(av??-Infinity);return sort==="market"?desc(ac.value,bc.value):sort==="msrp"?b.msrp-a.msrp:sort==="profit"?desc(ac.profit,bc.profit):sort==="name"?a.name.localeCompare(b.name):desc(ac.profitPct,bc.profitPct)})},[products,setFilter,query,sort,basis,keepPct,taxOn,taxRate,shipping,profitableOnly]);
 const metrics=useMemo(()=>{const rows=filtered.map(calculate),priced=rows.filter(row=>row.value!=null),profitable=priced.filter(row=>(row.profit??0)>0).length,premiums=priced.map(row=>row.profitPct!).sort((a,b)=>a-b);return{profitable:priced.length?profitable/priced.length*100:0,median:premiums.length?premiums[Math.floor(premiums.length/2)]:0,market:priced.reduce((sum,row)=>sum+row.value!,0),count:rows.length}},[filtered,basis,keepPct,taxOn,taxRate,shipping]);
 const pages=Math.max(1,Math.ceil(filtered.length/perPage)),visible=filtered.slice((page-1)*perPage,page*perPage);
 return <section className="sealed-market" id="sealed-market">
  <div className="sealed-summary"><div><p className="kicker">Sealed product intelligence</p><h2>{games[game]} Sealed</h2><p>Verified MSRP compared with current TCGplayer pricing.</p></div><div className="price-basis" aria-label="Price basis"><button className={basis==="market"?"active":""} onClick={()=>setBasis("market")}>Market</button><button className={basis==="median"?"active":""} onClick={()=>setBasis("median")}>Median</button></div></div>
  <div className="sealed-kpis"><div><span>Products</span><strong>{metrics.count}</strong><small>verified MSRP</small></div><div><span>Median return</span><strong className={metrics.median>=0?"profit-positive":"profit-negative"}>{metrics.median>=0?"+":""}{metrics.median.toFixed(1)}%</strong><small>across selection</small></div><div><span>Profitable</span><strong>{metrics.profitable.toFixed(0)}%</strong><small>above adjusted cost</small></div><div><span>Market value</span><strong>{usd(metrics.market)}</strong><small>one of each product</small></div></div>
  <div className="sealed-controls">
   <label><span>Market</span><select value={game} onChange={event=>setGame(event.target.value as Game)}><option value="pokemon">Pokémon</option><option value="onepiece">One Piece</option><option value="riftbound">Riftbound</option><option value="magic">Magic: The Gathering</option></select></label>
   <label><span>Set</span><select value={setFilter} onChange={event=>{setSetFilter(event.target.value);setPage(1)}}><option value="all">All sets</option>{sets.map(value=><option key={value}>{value}</option>)}</select></label>
   <label className="sealed-search"><span>Search</span><input value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder="Search product or set"/></label>
   <label><span>Sort</span><select value={sort} onChange={event=>setSort(event.target.value)}><option value="profitPct">Profit %</option><option value="profit">Profit $</option><option value="market">Selected value</option><option value="msrp">MSRP</option><option value="name">Product name</option></select></label>
   <label><span>Per page</span><select value={perPage} onChange={event=>{setPerPage(Number(event.target.value));setPage(1)}}><option>20</option><option>30</option><option>40</option><option>50</option></select></label>
  </div>
  <div className="profit-tools" aria-label="Profit assumptions">
   <label><span>Keep after fees</span><span className="input-suffix"><input type="number" min="1" max="100" value={keepPct} onChange={event=>setKeepPct(Math.min(100,Math.max(1,Number(event.target.value))))}/><b>%</b></span></label>
   <label className="check-control"><input type="checkbox" checked={taxOn} onChange={event=>setTaxOn(event.target.checked)}/><span>Include sales tax</span></label>
   <label><span>Tax rate</span><span className="input-suffix"><input type="number" min="0" max="20" step="0.1" disabled={!taxOn} value={taxRate} onChange={event=>setTaxRate(Math.max(0,Number(event.target.value)))}/><b>%</b></span></label>
   <label><span>Shipping cost</span><span className="input-prefix"><b>$</b><input type="number" min="0" step="0.5" value={shipping} onChange={event=>setShipping(Math.max(0,Number(event.target.value)))}/></span></label>
   <label className="check-control"><input type="checkbox" checked={profitableOnly} onChange={event=>{setProfitableOnly(event.target.checked);setPage(1)}}/><span>Profitable only</span></label>
  </div>
  <div className="sealed-head"><span>Product</span><span>Set</span><span>MSRP</span><span>{basis==="market"?"Market":"Median"}</span><span>Profit</span><span>Profit %</span></div>
  <div className="sealed-rows">{loading?<div className="empty">Loading sealed products…</div>:visible.map(product=>{const result=calculate(product),priced=result.value!=null;return <a className="sealed-row" href={product.url} target="_blank" rel="noreferrer" key={product.productId}><span className="sealed-product"><DeferredImage src={product.image} alt=""/><span><b>{product.name}</b><small>{product.category}</small></span></span><span className="sealed-category">{product.set}</span><span data-label="MSRP"><b>{usd(product.msrp)}</b><small>{taxOn?`Cost ${usd(result.cost)}`:product.msrpSource}</small></span><span data-label={basis==="market"?"Market":"Median"}><b>{usd(result.value)}</b><small>{priced?(keepPct<100?`Proceeds ${usd(result.proceeds)}`:"TCGplayer value"):"No TCGplayer data"}</small></span><span data-label="Profit" className={!priced?"":result.profit!>=0?"profit-positive":"profit-negative"}><b>{!priced?"N/A":`${result.profit!>=0?"+":""}${usd(result.profit)}`}</b></span><span data-label="Profit %"><b className={`profit-pill ${!priced?"unavailable":result.profitPct!>=0?"positive":"negative"}`}>{!priced?"N/A":`${result.profitPct!>=0?"+":""}${result.profitPct!.toFixed(1)}%`}</b></span></a>})}</div>
  {!loading&&<div className="pagination"><button disabled={page===1} onClick={()=>setPage(value=>value-1)}>← Previous</button><span>Page <b>{page}</b> of {pages}</span><button disabled={page===pages} onClick={()=>setPage(value=>value+1)}>Next →</button></div>}
  <p className="sealed-note">Profit uses the selected price basis and assumptions above. Defaults compare TCGplayer market directly with published US MSRP; fees, tax, and shipping are optional scenario inputs, not predictions.</p>
 </section>
}
