"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps -- keyed effects synchronize remote sealed data and history */
import {useEffect,useMemo,useState} from "react";
import DeferredImage from "./DeferredImage";
import {type PricePoint} from "./PriceChart";
import HistoryPanel,{movementTone} from "./HistoryPanel";
import {NumberedPagination,SegmentedView,SortableHeader,SortToolbar,type Direction} from "./MarketUI";
import {mapWithConcurrency,nearestChange,rangeStats} from "./market-utils";
import SealedFilters from "./SealedFilters";
import {SignalBadge,StrictnessControl} from "./SignalControls";
import {marketSignal,type SignalSide,type SignalStrictness} from "./signal-utils";
import MultiSelectField from "./MultiSelectField";
import SaleScenario from "./SaleScenario";

type Game="pokemon"|"onepiece"|"riftbound"|"magic"; type Basis="market"|"median"; type View="medium"|"text"|"full"; type SortKey="name"|"signal"|"set"|"msrp"|"market"|"profit"|"profitPct";
type Product={game:Game;productId:number;name:string;set:string;category:string;image:string|null;url:string;msrp:number|null;marketPrice:number|null;midPrice:number|null;profit:number|null;profitPct:number|null;msrpSource:string|null};
type History={points:PricePoint[];variant?:string;condition?:string;coverage:"exact"|"fallback"|"none";change7:number|null;change30:number|null;change90:number|null;low30:number|null;high30:number|null;historyLow:number|null};
const games:Record<Game,string>={pokemon:"Pokémon",onepiece:"One Piece",riftbound:"Riftbound",magic:"Magic: The Gathering"},views:{key:View;label:string;icon:string}[]=[{key:"medium",label:"Medium",icon:"▤"},{key:"text",label:"Text",icon:"☷"},{key:"full",label:"Full",icon:"▥"}];
const sealedSorts:{label:string;key:SortKey}[]=[{label:"Product",key:"name"},{label:"Set",key:"set"},{label:"MSRP",key:"msrp"},{label:"Market",key:"market"},{label:"Profit",key:"profit"},{label:"Profit %",key:"profitPct"}];
const sealedSignalSort={label:"Signal",key:"signal" as SortKey};
const usd=(value:number|null)=>value==null?"N/A":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:value>=100?0:2}).format(value);
const pct=(value:number|null)=>value==null?"N/A":`${value>=0?"+":""}${value.toFixed(1)}%`;
const nullableSort=(a:number|null,b:number|null,direction:Direction)=>a==null?1:b==null?-1:direction==="asc"?a-b:b-a;
const typeOrder=["Booster Packs","Booster Boxes","Booster Bundles","Starter / Theme Decks","Elite Trainer Boxes","Build & Battle","Collections","Tins","Blisters","Trainer Kits / Toolkits","Cases","Boxes / Bundles","Other"];
const productType=(product:Product)=>typeOrder.includes(product.category)?product.category:"Other";

export default function SealedView({signalView="leaderboard",strictness="balanced",onStrictness=()=>{}}:{signalView?:SignalSide;strictness?:SignalStrictness;onStrictness?:(value:SignalStrictness)=>void}){
 const [game,setGame]=useState<Game>("pokemon"),[products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[selectedSets,setSelectedSets]=useState<string[]>([]),[selectedTypes,setSelectedTypes]=useState<string[]>([]),[marketMin,setMarketMin]=useState(""),[marketMax,setMarketMax]=useState(""),[msrpMin,setMsrpMin]=useState(""),[msrpMax,setMsrpMax]=useState(""),[profitMin,setProfitMin]=useState(""),[profitMax,setProfitMax]=useState(""),[profitPctMin,setProfitPctMin]=useState(""),[profitPctMax,setProfitPctMax]=useState(""),[sort,setSort]=useState<SortKey>("profitPct"),[direction,setDirection]=useState<Direction>("desc"),[perPage,setPerPage]=useState(20),[page,setPage]=useState(1),[view,setView]=useState<View>("medium"),[history,setHistory]=useState<Record<number,History>>({}),[touchOpen,setTouchOpen]=useState<number|null>(null);
 const [basis,setBasis]=useState<Basis>("market"),[keepPct,setKeepPct]=useState(100),[taxOn,setTaxOn]=useState(false),[taxRate,setTaxRate]=useState(8),[shipping,setShipping]=useState(0),[profitableOnly,setProfitableOnly]=useState(false);
 useEffect(()=>{let active=true;setLoading(true);fetch(`/data/sealed-${game}.json`).then(response=>response.json()).then(data=>{if(active){setProducts(data);setLoading(false);setPage(1);setSelectedSets([]);setSelectedTypes([])}});return()=>{active=false}},[game]);
 useEffect(()=>{setSort(signalView==="leaderboard"?"profitPct":"signal");setDirection("desc");setPage(1)},[signalView]);
 const sets=useMemo(()=>[...new Set(products.map(product=>product.set))].sort(),[products]),productTypes=useMemo(()=>[...new Set(products.map(productType))].sort((a,b)=>typeOrder.indexOf(a)-typeOrder.indexOf(b)),[products]);
 const calculate=(product:Product)=>{const value=basis==="median"?(product.midPrice??product.marketPrice):product.marketPrice,cost=product.msrp==null?null:product.msrp*(taxOn?1+taxRate/100:1)+shipping;if(value==null||cost==null)return{value,cost,proceeds:value==null?null:value*keepPct/100,profit:null,profitPct:null};const proceeds=value*keepPct/100,profit=proceeds-cost;return{value,cost,proceeds,profit,profitPct:cost?profit/cost*100:0}};
 const signalFor=(product:Product)=>signalView==="leaderboard"?null:marketSignal(history[product.productId]?.points??[],signalView,strictness,calculate(product).value);
 const filtered=useMemo(()=>{const needle=query.trim().toLowerCase();return products.filter(product=>{const result=calculate(product),value=result.value;return(!selectedSets.length||selectedSets.includes(product.set))&&(!selectedTypes.length||selectedTypes.includes(productType(product)))&&(!needle||`${product.name} ${product.set} ${product.category} ${productType(product)}`.toLowerCase().includes(needle))&&(!marketMin||value!=null&&value>=Number(marketMin))&&(!marketMax||value!=null&&value<=Number(marketMax))&&(!msrpMin||product.msrp!=null&&product.msrp>=Number(msrpMin))&&(!msrpMax||product.msrp!=null&&product.msrp<=Number(msrpMax))&&(!profitMin||result.profit!=null&&result.profit>=Number(profitMin))&&(!profitMax||result.profit!=null&&result.profit<=Number(profitMax))&&(!profitPctMin||result.profitPct!=null&&result.profitPct>=Number(profitPctMin))&&(!profitPctMax||result.profitPct!=null&&result.profitPct<=Number(profitPctMax))&&(!profitableOnly||(result.profit??-Infinity)>0)&&(signalView==="leaderboard"||Boolean(signalFor(product)))}).sort((a,b)=>{const ac=calculate(a),bc=calculate(b);if(sort==="signal")return nullableSort(signalFor(a)?.score??null,signalFor(b)?.score??null,direction);if(sort==="msrp")return nullableSort(a.msrp,b.msrp,direction);if(sort==="market")return nullableSort(ac.value,bc.value,direction);if(sort==="profit")return nullableSort(ac.profit,bc.profit,direction);if(sort==="profitPct")return nullableSort(ac.profitPct,bc.profitPct,direction);const value=sort==="name"?a.name.localeCompare(b.name):a.set.localeCompare(b.set)||a.name.localeCompare(b.name);return direction==="asc"?value:-value})},[products,selectedSets,selectedTypes,marketMin,marketMax,msrpMin,msrpMax,profitMin,profitMax,profitPctMin,profitPctMax,query,sort,direction,basis,keepPct,taxOn,taxRate,shipping,profitableOnly,history,signalView,strictness]);
 const metrics=useMemo(()=>{const rows=filtered.map(calculate),priced=rows.filter(row=>row.value!=null);return{market:priced.reduce((sum,row)=>sum+row.value!,0),count:rows.length}},[filtered,basis,keepPct,taxOn,taxRate,shipping]);
 const pages=Math.max(1,Math.ceil(filtered.length/perPage)),visible=filtered.slice((page-1)*perPage,page*perPage);
 useEffect(()=>{let active=true;const targets=signalView==="leaderboard"?visible:products.slice(0,400),missing=targets.filter(product=>product.productId>0&&!history[product.productId]);if(!missing.length)return;mapWithConcurrency(missing,4,async product=>{try{const response=await fetch(`/api/history?productId=${product.productId}&printing=Normal&sealed=1`);if(!response.ok)throw new Error();const data=await response.json(),points:PricePoint[]=data.points??[],range=rangeStats(points,30);return[product.productId,{...data,points,change7:nearestChange(points,7),change30:nearestChange(points,30),change90:nearestChange(points,90),low30:range.low,high30:range.high,historyLow:points.length?Math.min(...points.map(point=>point.price)):null}] as const}catch{return[product.productId,{points:[],coverage:"none",change7:null,change30:null,change90:null,low30:null,high30:null,historyLow:null}] as const}}).then(entries=>{if(active)setHistory(old=>({...old,...Object.fromEntries(entries)}))});return()=>{active=false}},[(signalView==="leaderboard"?visible:products.slice(0,400)).map(product=>product.productId).join(","),signalView,strictness]);
 const changeSort=(next:SortKey)=>{setDirection(current=>sort===next?(current==="asc"?"desc":"asc"):(next==="name"||next==="set"?"asc":"desc"));setSort(next);setPage(1)};
 const rowDetails=(product:Product,result:ReturnType<typeof calculate>,h?:History,large=false)=>{const movement=(label:string,value:number|null|undefined)=>({label,value:value===undefined?"…":pct(value??null),tone:movementTone(value)});return <HistoryPanel title={h?.condition??"Sealed market history"} subtitle={h?.variant??product.category} points={h?.points??[]} label="sealed market" metrics={[{label:"MSRP",value:usd(product.msrp)},{label:basis,value:usd(result.value)},{label:"30D low",value:usd(h?.low30??null)},{label:"30D high",value:usd(h?.high30??null)},{label:"Hist low",value:usd(h?.historyLow??null)},{label:"Profit",value:usd(result.profit),tone:movementTone(result.profit)},{label:"Profit %",value:pct(result.profitPct),tone:movementTone(result.profitPct)},movement("7 day",h?.change7),movement("30 day",h?.change30),movement("90 day",h?.change90)]} large={large}/>};
 const activeSorts=signalView==="leaderboard"?sealedSorts:[sealedSorts[0],sealedSignalSort,...sealedSorts.slice(1)];
 const summaryFilters=[query?{key:"query",label:`Search: ${query}`,clear:()=>setQuery("")}:null,selectedTypes.length?{key:"types",label:`${selectedTypes.length} Product Type${selectedTypes.length===1?"":"s"}`,clear:()=>setSelectedTypes([])}:null,selectedSets.length?{key:"sets",label:`${selectedSets.length} Set${selectedSets.length===1?"":"s"}`,clear:()=>setSelectedSets([])}:null,marketMin||marketMax?{key:"market",label:`Market: ${marketMin||"Any"}–${marketMax||"Any"}`,clear:()=>{setMarketMin("");setMarketMax("")}}:null,msrpMin||msrpMax?{key:"msrp",label:`MSRP: ${msrpMin||"Any"}–${msrpMax||"Any"}`,clear:()=>{setMsrpMin("");setMsrpMax("")}}:null,profitMin||profitMax?{key:"profit",label:`Profit: ${profitMin||"Any"}–${profitMax||"Any"}`,clear:()=>{setProfitMin("");setProfitMax("")}}:null,profitPctMin||profitPctMax?{key:"profitPct",label:`Profit %: ${profitPctMin||"Any"}–${profitPctMax||"Any"}`,clear:()=>{setProfitPctMin("");setProfitPctMax("")}}:null,profitableOnly?{key:"profitable",label:"Profitable Only",clear:()=>setProfitableOnly(false)}:null].filter((item):item is {key:string;label:string;clear:()=>void}=>Boolean(item));
 return <section className="sealed-market" id="sealed-market"><section className="market-strip sealed-market-strip"><label><span>Market</span><select aria-label="Sealed market" value={game} onChange={event=>{setGame(event.target.value as Game);setSelectedSets([]);setSelectedTypes([]);setPage(1)}}><option value="pokemon">Pokémon</option><option value="onepiece">One Piece</option><option value="riftbound">Riftbound</option><option value="magic">Magic: The Gathering</option></select></label><MultiSelectField label="Product type" options={productTypes.map(type=>({key:type,label:type}))} selected={selectedTypes} onChange={values=>{setSelectedTypes(values);setPage(1)}} allLabel="All product types" searchable={false}/><div><span>Products available</span><strong>{metrics.count.toLocaleString()}</strong><small>{usd(metrics.market)} combined market</small></div><label><span>Products per page</span><select aria-label="Sealed products per page" value={perPage} onChange={event=>{setPerPage(Number(event.target.value));setPage(1)}}><option>20</option><option>30</option><option>40</option><option>50</option></select></label></section>
 <div className="sealed-summary"><div><p className="kicker">Sealed product intelligence</p><h2>{games[game]} {signalView==="leaderboard"?"Sealed":signalView==="buy"?"Hot Buys":"Hot Sells"}</h2><p>{signalView==="leaderboard"?"Verified MSRP compared with current TCGplayer pricing.":`${strictness[0].toUpperCase()+strictness.slice(1)} signals ranked by proximity, volatility, and data confidence.`}</p><div className={`leader-filter-summary ${summaryFilters.length||signalView!=="leaderboard"?"has-content":""}`} aria-label="Active sealed filters" aria-hidden={!summaryFilters.length&&signalView==="leaderboard"}><b>{filtered.length.toLocaleString()} Matches</b>{signalView!=="leaderboard"&&<span className="summary-signal">{strictness[0].toUpperCase()+strictness.slice(1)} Signals</span>}{summaryFilters.map(item=><button type="button" key={item.key} title={`Remove ${item.label} filter`} aria-label={`Remove ${item.label} filter`} onClick={()=>{item.clear();setPage(1)}}>{item.label}<i aria-hidden="true">×</i></button>)}</div></div><div className="price-basis" aria-label="Price basis"><i aria-hidden="true"/><button className={basis==="market"?"active":""} onClick={()=>setBasis("market")}>Market</button><button className={basis==="median"?"active":""} onClick={()=>setBasis("median")}>Median</button></div></div>
 <SaleScenario keepPct={keepPct} onKeepPct={setKeepPct} taxOn={taxOn} onTaxOn={setTaxOn} taxRate={taxRate} onTaxRate={setTaxRate} shipping={shipping} onShipping={setShipping}/>
 <div className={`sealed-toolbar ${signalView!=="leaderboard"?"has-strictness":""}`}><label className="sealed-toolbar-search"><span>⌕</span><input value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder="Search product, set, or type"/></label>{signalView!=="leaderboard"&&<StrictnessControl value={strictness} onChange={value=>{onStrictness(value);setPage(1)}}/>}<SealedFilters sets={sets} selectedSets={selectedSets} onSets={values=>{setSelectedSets(values);setPage(1)}} marketMin={marketMin} marketMax={marketMax} onMarketMin={value=>{setMarketMin(value);setPage(1)}} onMarketMax={value=>{setMarketMax(value);setPage(1)}} msrpMin={msrpMin} msrpMax={msrpMax} onMsrpMin={value=>{setMsrpMin(value);setPage(1)}} onMsrpMax={value=>{setMsrpMax(value);setPage(1)}} profitMin={profitMin} profitMax={profitMax} onProfitMin={value=>{setProfitMin(value);setPage(1)}} onProfitMax={value=>{setProfitMax(value);setPage(1)}} profitPctMin={profitPctMin} profitPctMax={profitPctMax} onProfitPctMin={value=>{setProfitPctMin(value);setPage(1)}} onProfitPctMax={value=>{setProfitPctMax(value);setPage(1)}} profitableOnly={profitableOnly} onProfitableOnly={value=>{setProfitableOnly(value);setPage(1)}} onReset={()=>{setSelectedSets([]);setMarketMin("");setMarketMax("");setMsrpMin("");setMsrpMax("");setProfitMin("");setProfitMax("");setProfitPctMin("");setProfitPctMax("");setProfitableOnly(false);setPage(1)}}/><SegmentedView value={view} options={views} label="Sealed product view" onChange={next=>{setView(next);setPage(1)}}/></div>
 {view==="full"?<SortToolbar items={activeSorts.map(item=>item.key==="market"?{...item,label:basis==="market"?"Market":"Median"}:item)} sort={sort} direction={direction} onSort={changeSort} label="Full sealed product sorting"/>:<div className={`sealed-head ${signalView!=="leaderboard"?"has-signal":""}`}>{activeSorts.map(item=><SortableHeader key={item.key} label={item.key==="market"?(basis==="market"?"Market":"Median"):item.label} column={item.key} sort={sort} direction={direction} onSort={changeSort}/>)}</div>}
 <div className={`sealed-rows sealed-view-${view}`}>{loading?<div className="row-skeletons" aria-label="Loading sealed products">{Array.from({length:8},(_,i)=><span key={i}/>)}</div>:visible.map(product=>{const result=calculate(product),h=history[product.productId],priced=result.value!=null,comparable=result.profit!=null,signal=signalFor(product),columnSignal=signal&&(view==="medium"||view==="text");if(view==="full")return <span className="signal-card-wrap" key={product.productId}>{signal&&<SignalBadge signal={signal}/>}<a className="sealed-full-card" href={product.url} target="_blank" rel="noreferrer"><span className="sealed-full-art"><DeferredImage src={product.image} alt={`${product.name} product`}/></span><span className="sealed-full-data"><span className="sealed-full-title"><b>{product.name}</b><small>{product.set} · {product.category}</small></span>{rowDetails(product,result,h)}</span><span className="arrow">↗</span></a></span>;return <a className={`sealed-row ${columnSignal?"has-signal":""} ${touchOpen===product.productId?"touch-open":""}`} href={product.url} target="_blank" rel="noreferrer" key={product.productId} onClick={event=>{if(window.matchMedia("(hover: none)").matches&&touchOpen!==product.productId){event.preventDefault();setTouchOpen(product.productId)}}}><span className="sealed-product"><DeferredImage src={product.image} alt=""/><span><b>{product.name}</b><small>{product.category}</small></span></span>{columnSignal&&<span className="sealed-signal-cell"><SignalBadge signal={signal!}/></span>}<span className="sealed-category">{product.set}</span><span data-label="MSRP"><b>{usd(product.msrp)}</b><small>{product.msrp==null?"MSRP unavailable":taxOn?`Cost ${usd(result.cost)}`:product.msrpSource}</small></span><span data-label={basis==="market"?"Market":"Median"}><b>{usd(result.value)}</b><small>{priced?(keepPct<100?`Proceeds ${usd(result.proceeds)}`:"TCGplayer value"):"No TCGplayer data"}</small></span><span data-label="Profit" className={!comparable?"":result.profit!>=0?"profit-positive":"profit-negative"}><b>{!comparable?"N/A":`${result.profit!>=0?"+":""}${usd(result.profit)}`}</b></span><span data-label="Profit %"><b className={`profit-pill ${!comparable?"unavailable":result.profitPct!>=0?"positive":"negative"}`}>{!comparable?"N/A":`${result.profitPct!>=0?"+":""}${result.profitPct!.toFixed(1)}%`}</b></span><span className="sealed-hover-card"><span className="sealed-hover-art"><DeferredImage src={product.image} alt={`${product.name} product`}/></span><span>{rowDetails(product,result,h)}<small className="touch-hint">Tap again to open TCGplayer ↗</small></span></span></a>})}</div>
 {!loading&&<NumberedPagination page={page} pages={pages} onChange={setPage} label="Sealed product pages"/>}<p className="sealed-note">Profit uses the selected price basis and assumptions above. Defaults compare TCGplayer market directly with published US MSRP; fees, tax, and shipping are optional scenario inputs, not predictions.</p></section>
}
